services:
  - type: web
    name: tindimithra
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tindimithra.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: tindimithra-db
          property: connectionString

databases:
  - name: tindimithra-db
    databaseName: tindimithra
    user: tindimithra
    plan: free 